### ISSUE TITLE
アーカイブ化を提案します

### ISSUE THREAD

**Issue by kojix2** [sciruby-jp/sciruby-jp.reactapp#2]
Rubyのデータ分析を取り巻く状況は、2019年のRumaleの普及、GPUで計算可能なCumoの登場、RedChainerやruby-dnnといったDeepLearningライブラリの登場、そして、おそらく2020年に起きるであろうApacheArrowの普及によって大きく変化しつつあります。

とくにRumale登場のインパクトは大きく、この1年でRubyをめぐるデータ処理の環境は大きく好転したと個人的には考えています。

グーグル検索の対策上、古い情報は残すべきではないと思います。
更新の目処が立たないためアーカイブ化してサイトを閉鎖することを提案します。

**Comment by kozo2** [comment]
本リポジトリとデプロイ用プロジェクトのアーカイブ化ならびに
デプロイ用プロジェクトのリネームによるサイト閉鎖を行いました。
